name: Wastelands
version: ${project.version}
main: henry232323.wastelands.Wastelands
authors: [henry232323]
description: A plugin for ResortCraft's Wastelands gamemode
depends: [Vault, GroupManager]

permissions:
  wastelands.*:
    description: All permissions for wastelands
    children:
      wastelands.reload: true
      wastelands.bounties: true
      wastelands.setbounty: true
      wastelands.bounty.claim: true
      wastelands.checkrank: true
      wastelands.leaderboard: true
  wastelands.reload:
    description: Gives access to reloading the plugin
    default: op
  wastelands.bounties:
    description: View the available bounties for the server or for a player
    default: true
  wastelands.setbounty:
    description: Gives access to viewing the leaderboard
    default: true
  wastelands.bounty.claim:
    description: Allows players to claim bounties in the given world
    default: false
  wastelands.leaderboard:
    description: Check the kill leaderboard for Wastelands
    default: true
  wastelands.checkrank:
    description: Check a player's current rank overall
    default: true

commands:
  bounties:
    description: View the leaderboard for a parkour
    permission: wastelands.bounties
    usage: "§cSyntax error! Usage: /bounties OR /bounties <player>"
  setbounty:
    description: Set a bounty on another player
    permission: wastelands.setbounty
    usage: "§cSyntax error! Usage: /setbounty <player> <amount>"
  wastelands:
    description: Reload the Wastelands plugin
    permission: wastelands.reload
    usage: "§cSyntax error! Usage: /wastelands <reload>"
  leaderboard:
    description: Check the kill leaderboard for Wastelands
    permission: wastelands.leaderboard
    usage: "§cSyntax error! Usage: /leaderboard"
  checkrank:
    description: Check a player's current rank overall
    permission: wastelands.checkrank
    usage: "§cSyntax error! Usage: /checkrank <player>"